### ISSUE TITLE
GitHub Copilot for Azure can't finish Azure account login process

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/GitHub-Copilot-for-Azure#10]
- Copilot Chat Extension Version: 0.3.7
- VS Code Version: 1.95.1
- OS Version: Mac OS 11.7.10
- Logs: 
  on VS Code Chat windows:
  An error occurred while trying to determine if you have access to @azure: Failed to get an Azure Copilot access check token.

  on Edge browser error page:
  Error Code: 53003
  Request Id: 64180647-1309-4c1b-995a-40a699b95400
  Correlation Id: 6b0d2c4e-da68-40f2-a9c0-fab097fa2a32
  Timestamp: 2024-11-03T06:47:54.080Z
  Application Name: Visual Studio Code
  Application ID: aebc6443-996d-45c2-90f0-388ff96faa56
  IP address: 223.166.202.144
  设备标识符: 不可用
  设备平台: macOS
  设备状态: Unregistered

Steps to Reproduce:

1. Open GitHub Copilot Chat and type in ‘@azure’ and questions like ‘How to create a web server resource with the lowest price in Azure?‘
2. GitHub Copilot for Azure prompt need to register or login to the Azure account
3. When I click ’login‘， Edge browser opens and I log in by my MSA account which is also used as GitHub login and Azure extension login
4. The Error page shows login successes but have not permission to access
5. I can use GitHub Copilot Chat normally simultaneously with other topics like @websearch, @workspace, etc.

My MSA account has some Azure subscriptions and has also been added to Microsoft Entra as a guest account. I guess that issue may be due to Microsoft's guest account policy. Could you please help me to check on it? Or let me select subscription after login.

**Comment by bwateratmsft** [comment]
@HaoHoo can you share the output from the "@azure" output log?

**Comment by tmeschter** [comment]
@HaoHoo Also, could you try `@azure /changeTenant` to pick a different Azure tenant to work with and try again after that?

**Comment by kvenkatrajan** [comment]
@HaoHoo - checking back in. Did you have a chance to try the suggestion above?

**Comment by HaoHoo** [comment]
> [@HaoHoo](https://github.com/HaoHoo) Also, could you try `@azure /changeTenant` to pick a different Azure tenant to work with and try again after that?

- I've tried this action. But looks like that must be after the login process. I was just trapped in the login process.

**Comment by HaoHoo** [comment]
> [@HaoHoo](https://github.com/HaoHoo) can you share the output from the `@azure` output log? As well as the "Microsoft Authentication" output log?

I am on Mac OS and do you mind telling me how to collect these logs? Thank you.

**Comment by HaoHoo** [comment]
> [@HaoHoo](https://github.com/HaoHoo) Also, could you try `@azure /changeTenant` to pick a different Azure tenant to work with and try again after that?

Oh, I meant to skip verifying the Azure account when logging in and check on it after logging in. I guess Microsoft Entra policy denied enumerating the tenant for the guest account.

**Comment by HaoHoo** [comment]
> [@HaoHoo](https://github.com/HaoHoo) Also, could you try `@azure /changeTenant` to pick a different Azure tenant to work with and try again after that?



> [@HaoHoo](https://github.com/HaoHoo) can you share the output from the `@azure` output log? As well as the "Microsoft Authentication" output log?

Sorry, I pasted the log below but I think it may not help. Because looks like I've logged in after inputting @azure /changeTenant, Even the MSA login page still shows login successfully but resource access is denied.

 Now I can see the GitHub Copiloy for Azure extension has been ticked in 'manage trusted extensions' from Github, GitHub Copilot Chat, and Microsoft accounts.

If you need I think I can log off and try again for the logs.

**Comment by NileshGule** [comment]
I tried using the /changeTenant option and it worked for me on MacOS with Visual Studio Code

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

**Comment by tmeschter** [comment]
Hi @HaoHoo. Thank you for the updates.

If I understand correctly, after running `@azure /changeTenant` you were able to log-in successfully? And then some `@azure` functionality works, but not everything?
