### ISSUE TITLE
After asking first question to agent, the AKS help page shows up

### ISSUE THREAD

**Issue by timheuer** [microsoft/GitHub-Copilot-for-Azure#13]
Type: <b>Bug</b>

When I start interacting with the Azure agent the AKS help documentation pops up even though I didn't say anything about AKS

![Image](https://github.com/user-attachments/assets/0d8c3b3d-0dab-4222-896b-deae7ad920ef)

Extension version: 0.3.7
VS Code version: Code - Insiders 1.96.0-insider (f87f8a56f3a30238076bee3db39c245bd69be264, 2024-11-05T05:04:15.310Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (8.93GB free)|
|Process Argv|--crash-reporter-id 5f5d2ab1-465c-4ddc-809d-58d91db5dfb0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by bwateratmsft** [comment]
This is coming from the AKS extension. Did you install it before interacting with `@azure`?

**Comment by timheuer** [comment]
I already have it installed yes...felt like something is activating it in the GH for Azure agent.

**Comment by bwateratmsft** [comment]
That makes sense, we have to activate the AKS extension to get the plugins it's contributing to `@azure`. I wonder if they're showing their walkthrough on activation, it should normally only be shown on install.

**Comment by charris-msft** [comment]
Thanks @timheuer !!

I've noticed the AKS extension Welcome page was open a couple of times and had wondered why in the back of my mind. Just this morning, I realized it might be opening when invoking @azure, but I didn't have time to dig deeper. I did just repro it right now though.

I'll mention this to the AKS team.
