### ISSUE TITLE
Prompt returns storage accounts across all subscriptions when inquired the first time in the chat history

### ISSUE THREAD

**Issue by kvenkatrajan** [microsoft/GitHub-Copilot-for-Azure#14]
**Prompt** : can you tell me the storage accounts for the "XYZ" subscription?
**Behavior** : With access to multiple subscriptions and with the azure resource extension installed, it gives the storage accounts across all the subscriptions instead of the specified subscription. The second time its prompted within the same chat conversation it provides the right results
**Actual**:  It displays the resources associated with the specific subscription

**Comment by bwateratmsft** [comment]
I tried this out and the query that is passed to ARG plugin is something too generic like "list all storage accounts".

**Comment by bwateratmsft** [comment]
Fixed in next release.
