### ISSUE TITLE
Thumbs up/down do not always appear, sometimes a new message is necessary

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/GitHub-Copilot-for-Azure#20]
In some cases (in particular, when we're deferring response parts), the thumbs up/down buttons do not appear. You have to send another message and then they appear. This is going to prevent us from getting feedback from end users.

I suspect this is an upstream issue.

/cc @isidorn

**Comment by isidorn** [comment]
@roblourens I can reproduce this. 
1. Install https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azure-github-copilot
2. Open chat view -> "How do I deploy this app to azure?"
3. Response does not have Thumbs Up / Thumbs Down

Might it be that we are awaiting on some part of the response? I assume we only render the Thumbs up / Thumbs down  once we know the response has completed. 

@bwateratmsft can you reproduce with a starter sample if you defer the response parts? Or can you provide more details on how you are deferring it in Azure?

**Comment by bwateratmsft** [comment]
I'll try to reproduce with the starter sample. I don't think there's anything particularly special about our "deferred response parts", they just get sent after the LLM is done.

**Comment by bwateratmsft** [comment]
@isidorn @roblourens I'm able to reproduce with the chat sample by simply sending a large Markdown chunk at the end of the response. Here's my fork/branch: https://github.com/bwateratmsft/vscode-extension-samples/tree/bmw/catchat

The changes are just this: https://github.com/bwateratmsft/vscode-extension-samples/commit/981b71b1f4c53f8fb719f5d0198a8d888e84c5ba

**Comment by roblourens** [comment]
Thanks- opened https://github.com/microsoft/vscode/issues/234034

**Comment by isidorn** [comment]
Thanks Rob and Brandon. I just tried it out with latest VS Code Insiders and it looks fixed for me with your latest changes Rob.
Brandon if you still see the issue do let us know.

**Comment by charris-msft** [comment]
Double-verified! Big thanks @bwateratmsft & @roblourens!
