### ISSUE TITLE
Login for @azure on VSCode Insiders fails with ApiContractViolation: (pii)

### ISSUE THREAD

**Issue by kvenkatrajan** [microsoft/GitHub-Copilot-for-Azure#25]
Issue : Login for @azure on VSCode Insiders fails with ApiContractViolation: (pii)

Temporary workaround:

- Install and use @azure in VSCode stable version (recommended)
OR
- Disable Use Msal in settings temporarily
![Image](https://github.com/user-attachments/assets/2bb33937-241c-4366-bbd8-340abe241f18)

**Comment by bwateratmsft** [comment]
This is now fixed.
