### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by ghost** [microsoft/GitHub-Copilot-for-Azure#39]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: This operating system and architecture is not supported by the GitHub Copilot for Azure extension. If you believe this is an error, please contact the extension authors.

Version: 0.3.58
OS: linux
OS Release: 6.5.0-1025-azure
Product: Visual Studio Code
Product Version: 1.95.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1805676
fulfilled extension.bundle.js:2:1803603
```

</details>

**Comment by bwateratmsft** [comment]
Is this an ARM64 or Alpine distribution of Linux?
