### ISSUE TITLE
problem with azure

### ISSUE THREAD

**Issue by tomasis7** [microsoft/GitHub-Copilot-for-Azure#41]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.3.61
OS: win32
OS Release: 10.0.22635
Product: Visual Studio Code
Product Version: 1.95.3
Language: en

<details>
<summary>Call Stack</summary>

```
knt.y workbench.desktop.main.js:3088:11662
knt.o workbench.desktop.main.js:3088:9130
knt.n workbench.desktop.main.js:3088:9021
async Object.factory workbench.desktop.main.js:3088:8771
```

</details>

**Comment by bwateratmsft** [comment]
Can you run "Preferences: Open User Settings (JSON)" and see what's wrong?

**Comment by tomasis7** [comment]
it worked when i logged in Azure.
