### ISSUE TITLE
forumi

### ISSUE THREAD

**Issue by Pixxelpirate** [microsoft/GitHub-Copilot-for-Azure#43]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Failed to acquire .NET runtime

Version: 0.3.61
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.95.3
Language: de

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1804577extension.bundle.js:2:1804577
fulfilled extension.bundle.js:2:1803733
```

</details>

**Comment by bwateratmsft** [comment]
Is there any output in the logs from `@azure` or `.NET Install Tool`?
