### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by amitjattan** [microsoft/GitHub-Copilot-for-Azure#47]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.3.61
OS: darwin
OS Release: 22.6.0
Product: Visual Studio Code
Product Version: 1.96.0
Language: en

**Comment by bwateratmsft** [comment]
@amitjattan is there anything in the output logs for `@azure`, `GitHub Authentication`, or `Microsoft Authentication`?

**Comment by amitjattan** [comment]
No activated agent with id "ms-azuretools.azure-agent" this is the error I get

**Comment by amitjattan** [comment]
> [@amitjattan](https://github.com/amitjattan) is there anything in the output logs for `@azure`, `GitHub Authentication`, or `Microsoft Authentication`?

Here is the error meesage from @azure command in VSCode - No activated agent with id "ms-azuretools.azure-agent"
