### ISSUE TITLE
GitHub Copilot for Azure not supported on devcontainer

### ISSUE THREAD

**Issue by ryanlwilliams** [microsoft/GitHub-Copilot-for-Azure#49]
Does this occur consistently? Yes or No
Repro steps:

1. Have GitHub CoPilot for Azure installed on the local machine
2. Connect to dev container using Ubuntu 24.04
3. Extension automatically installs to the dev container
4. Launch CoPilot chat

Error
This operating system and architecture is not supported by the GitHub Copilot for Azure extension. If you believe this is an error, please contact the extension authors.

**Comment by bwateratmsft** [comment]
Is this an ARM64 dev container? Or Alpine?

**Comment by ryanlwilliams** [comment]
This is devcontainer.json

```
{
	"name": "Ubuntu",
	"image": "mcr.microsoft.com/devcontainers/base:noble",
	"features": {
		"ghcr.io/devcontainers/features/azure-cli:1": {
			"installBicep": true,
			"version": "latest"
		}
	},
	"customizations": {
		"vscode": {
			"extensions": [
				"ms-azure-devops.azure-pipelines",
				"ms-vscode.vscode-node-azure-pack",
				"ms-azuretools.vscode-bicep"
			]
		}
	}
}
```
This is going to be ARM64 as its on a MacBook Pro M3

**Comment by bwateratmsft** [comment]
That explains it. Linux ARM64 is not currently supported, but it's something we're working on.
