### ISSUE TITLE
title

### ISSUE THREAD

**Issue by buynaa0314** [microsoft/GitHub-Copilot-for-Azure#50]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.3.61
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.96.0
Language: en

<details>
<summary>Call Stack</summary>

```
Not.y workbench.desktop.main.js:3109:6643
Not.o workbench.desktop.main.js:3109:4111
Not.n workbench.desktop.main.js:3109:4002
async Object.factory workbench.desktop.main.js:3109:3752
```

</details>

**Comment by bwateratmsft** [comment]
@buynaa0314 can you open your user settings JSON file and see what the error/warning is?
