### ISSUE TITLE
Not working I don't know why???

### ISSUE THREAD

**Issue by JeetMajumdar2003** [microsoft/GitHub-Copilot-for-Azure#51]
Does this occur consistently? yes for some days
Repro steps:

1. not updating, 
2. when i want to use it @ azure is gives no responce.

Action: azextAgent.activate
Error type: Error
Error Message: Canceled

Version: 0.3.61
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.96.0
Language: en

<details>
<summary>Call Stack</summary>

```
new c4s workbench.desktop.main.js:3145:37070
Fdt.U workbench.desktop.main.js:3145:41717
n.<computed>.r.charCodeAt.n.<computed> workbench.desktop.main.js:3145:39206
ass.getSessions workbench.desktop.main.js:781:63755
gWe.getSessions workbench.desktop.main.js:781:62465
O9t.z workbench.desktop.main.js:781:65864
O9t.$getSession workbench.desktop.main.js:781:67515
Fdt.S workbench.desktop.main.js:3145:41680
Fdt.Q workbench.desktop.main.js:3145:41458
Fdt.M workbench.desktop.main.js:3145:40546
```

</details>

**Comment by bwateratmsft** [comment]
@JeetMajumdar2003 can you share the output log from `@azure`?
