### ISSUE TITLE
Failed to Acquire .NET in VSCode

### ISSUE THREAD

**Issue by akefhabbal-qu** [microsoft/GitHub-Copilot-for-Azure#53]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Failed to acquire .NET runtime

Version: 0.3.61
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.96.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1804577extension.bundle.js:2:1804577
fulfilled extension.bundle.js:2:1803733
```

</details>

**Comment by bwateratmsft** [comment]
Can you share the output logs from `@azure` and `.NET Install Tool`?

**Comment by bwateratmsft** [comment]
Let us know if the issue reoccurs.
