### ISSUE TITLE
Action: azextAgent.activate

### ISSUE THREAD

**Issue by starin16** [microsoft/GitHub-Copilot-for-Azure#56]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Failed to acquire .NET runtime

Version: 0.3.61
OS: darwin
OS Release: 22.6.0
Product: Visual Studio Code
Product Version: 1.96.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1804577
fulfilled extension.bundle.js:2:1803733
```

</details>

**Comment by edfrutos** [comment]
An error occurred while installing .NET: .NET Acquisition Failed: .NET install timed out.
You should change the timeout if you have a slow connection. See: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts.
Our CDN may be blocked in China or experience significant slowdown, in which case you should install .NET manually., MESSAGE: Command failed: "/Users/edefrutos/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.2.3/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/edefrutos/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.11~x64~aspnetcore" -Version 8.0.11 -Verbose -Runtime aspnetcore -Architecture x64
dotnet_install: Error: Could not find `ASP.NET Core Runtime` with version = 8.0.11
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
, CODE: 1, SIGNAL: null, Error: .NET install timed out.
You should change the timeout if you have a slow connection. See: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#install-script-timeouts.
Our CDN may be blocked in China or experience significant slowdown, in which case you should install .NET manually., MESSAGE: Command failed: "/Users/edefrutos/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.2.3/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/edefrutos/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.11~x64~aspnetcore" -Version 8.0.11 -Verbose -Runtime aspnetcore -Architecture x64
dotnet_install: Error: Could not find `ASP.NET Core Runtime` with version = 8.0.11
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
, CODE: 1, SIGNAL: null
    at f.next (/Users/edefrutos/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/AcquisitionInvoker.js:69:50)
    at Generator.next (<anonymous>)
    at s (/Users/edefrutos/.vscode/extensions/vscode-dotnet-runtime-library/dist/Acquisition/AcquisitionInvoker.js:5:58)

**Comment by JasonYeMSFT** [comment]
Thanks to edfrutos for providing the details of the error. I am going to close this issue as duplicate and continue the investigation in #68 since it has the most information.
