### ISSUE TITLE
Change Tenant Issue

### ISSUE THREAD

**Issue by gsuttie** [microsoft/GitHub-Copilot-for-Azure#9]
I use my Github Account to login to VS Code and when I want to query my works Azure Tenant I dont seem to be able to do that again.

If i do @azure /changeTenant and supply my work tenant - Its a different email address but it prompst me only for the tenanats I have access to for my hotmail account.

I tried changing the tenant setting in VS Code which didnt work in the beta, then worked and now doesnt work in the public preview from what I see.

How do i change tenant and get tit to prompt me to sign in to Azure with different credentials?

**Comment by bwateratmsft** [comment]
You may need to sign out of your hotmail account and reset the `@azure.argTenant` setting to a blank value. VSCode is set up to use a certain account on a per-extension basis, so it has likely been configured to use your hotmail account.

**Comment by thomast1906** [comment]
I seem to reset `@azure.argTenant `to blank, but it still doesn't seem to undesrtand i want to attempt log in with another account and just defaults back to the current login?

**Comment by bwateratmsft** [comment]
You will need to sign out of your hotmail account in VSCode. You can do that here, bottom left of the screen:
![Image](https://github.com/user-attachments/assets/e9a392ab-c871-4f35-bc7e-e32f921a90f2)

**Comment by kvenkatrajan** [comment]
> feature request to make it more clearer on which account is using the extension, similar to GitHub CoPilot Chat

@Austinauth - Isn't the auth experience currently being revamped in VSCode? Has this UX been updated in the recent version?
